### ISSUE TITLE
Rename Marbula One's 2019 season to S01

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/JMR-stats#12]
Apparently the first season of Marbula One premiered in February of 2020, so rather than doing the results by year, I should do them by season.

Anywhere that there's 2019 in the Marbula One directory, change that to S01, and change the 2020 directory to S02.

**Comment by jamessral** [comment]
Could I do this for Hacktoberfest? It's perfect. My son loves Marbula One

**Comment by zo0o0ot** [comment]
https://jellesmarbleruns.fandom.com/wiki/Marbula_One_Season_1

**Comment by zo0o0ot** [comment]
Sure, go nuts.  I'm trying to write out issues to get everything up to snuff.

**Comment by zo0o0ot** [comment]
Resolved in #15
