### ISSUE TITLE
Update stats for Marbula E

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/JMR-stats#13]
https://jellesmarbleruns.fandom.com/wiki/Marbula_E#Races

Typical format of race results is four CSV files:

- seasonName-finishingRacePositions.csv
- seasonName-points.csv
- seasonName-qualifyingPositions.csv
- overallStandings.csv 

Link to Race 1:
https://youtu.be/7D-FHaaShvM

Link to Race 2:
https://youtu.be/k3S5bHEcmeg

Link to Race 3:
https://youtu.be/_xLOLGfFA5E

Link to Race 4:
https://youtu.be/uQrAqbLozaE

It looks like 6 races are scheduled, but only 4 races have been actually run.

**Comment by zo0o0ot** [comment]
Round 1 Qualifying:
![image](https://user-images.githubusercontent.com/876146/94887899-182c3a80-043d-11eb-9288-c93037371b79.png)

Round 1 Results:
![image](https://user-images.githubusercontent.com/876146/94887976-43168e80-043d-11eb-9d60-61d3ce455683.png)

Points after Round 1:
![image](https://user-images.githubusercontent.com/876146/94888007-5e819980-043d-11eb-9810-5cb5ca569ba9.png)

**Comment by zo0o0ot** [comment]
Round 2 Qualifying:
![image](https://user-images.githubusercontent.com/876146/94888095-a56f8f00-043d-11eb-99f6-04ba1df4b0b1.png)


Round 2 Results:
![image](https://user-images.githubusercontent.com/876146/94888142-c2a45d80-043d-11eb-9477-93af075a0ff0.png)


Points after round 2:
![image](https://user-images.githubusercontent.com/876146/94888158-d0f27980-043d-11eb-9114-64c4c3330897.png)

**Comment by zo0o0ot** [comment]
Round 3 Qualifying:
![image](https://user-images.githubusercontent.com/876146/94888211-f97a7380-043d-11eb-9b04-e9e260a80f55.png)

Round 3 Results:
![image](https://user-images.githubusercontent.com/876146/94888234-07c88f80-043e-11eb-9b5b-bd74ea9f03b5.png)

Points after Round 3:
![image](https://user-images.githubusercontent.com/876146/94888247-13b45180-043e-11eb-8a8b-e1a8c5217d43.png)

**Comment by zo0o0ot** [comment]
Round 4 Qualifying:
![image](https://user-images.githubusercontent.com/876146/94888291-38102e00-043e-11eb-8927-8d30a80126ff.png)

Round 4 Results:
![image](https://user-images.githubusercontent.com/876146/94888303-41999600-043e-11eb-9ca2-15a4dfea8f9b.png)

Points after Round 4:
![image](https://user-images.githubusercontent.com/876146/94888322-50804880-043e-11eb-9d38-05ed66405999.png)

**Comment by palash851** [comment]
assign to me

**Comment by zo0o0ot** [comment]
Have fun!

**Comment by zo0o0ot** [comment]
Data in https://github.com/zo0o0ot/JMR-stats/blob/1fe71d237fbf779efdd45a3f381aba30949d4882/MarbulaE/2020/2020-cumulative-points.csv#L1 is incorrect - by race totals are in there, and they need to be cumulative, but the list of racers and the order of the standings is correct.  Once that is done, I'll close this ticket.

**Comment by zo0o0ot** [comment]
Finished off in #31
